version: "3.3"
    
services:
  ddclient:
    build: ./ddclient/
    container_name: host_ddclient
    restart: always
      
  portainer:
    image: portainer/portainer-ce:latest
    container_name: host_portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
      - "9443:9443"
    restart: always
    
  nginx:
    build: ./nginx/
    container_name: host_nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always

volumes:
  portainer_data: {}