version: "3.3"
    
services:
      
  portainer:
    image: portainer/portainer-ce:latest
    container_name: host_portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_PROTO=https
      - VIRTUAL_HOST=portainer.localhost
      - VIRTUAL_PORT=9443
    ports:
      - "8000:8000"
      - "9443:9443"
    restart: always
  
  nginx-proxy:
    build: ./nginx-proxy/
    container_name: host_nginx_proxy
    environment:
      - DEFAULT_HOST=www.localhost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  ddclient:
    build: ./ddclient/
    container_name: host_ddclient
    restart: always

  nginx:
    build: ./nginx/
    container_name: host_nginx
    environment:
      - VIRTUAL_PROTO=http
      - VIRTUAL_HOST=www.localhost
      - VIRTUAL_PORT=80
    ports:
      - "22080:80"
      - "22443:443"
    restart: always

volumes:
  portainer_data: {}